<?php

namespace MeteoBundle\Repository;

use MeteoBundle\Controller;
use Doctrine\ORM\EntityRepository;

/**
 * MeteoVilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeteoVilleRepository extends EntityRepository
{
    public function findcountryid($id)
    {
        $time = new \DateTime();
        $time->modify('-1 hour');
        $qb = $this->createQueryBuilder('m');

        $qb->where('m.idCountry = :country')
            ->andwhere('m.time > :time')
            ->setParameter('country', $id)
            ->setParameter('time', $time)
            ->orderBy('m.time', 'DESC')
            ->setMaxResults('1')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
