<?php

namespace MeteoBundle\Repository;

/**
 * MeteoInputRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeteoInputRepository extends \Doctrine\ORM\EntityRepository
{
    public function findinput($villeClean)
    {
        $time = new \DateTime();
        $time->modify('-1 hour');
        $qb = $this->createQueryBuilder('m');

        $qb->where('m.input = :input')
            ->andwhere('m.time > :time')
            ->setParameter('input', $villeClean)
            ->setParameter('time', $time)
            ->orderBy('m.time', 'DESC')
            ->setMaxResults('1')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
